accelerator: gpu
accumulate_grad_batches: null
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 64
benchmark: null
check_val_every_n_epoch: 1
data: OFFICEHOME
data_dir: ./data/OFFICEHOME/
default_root_dir: null
detect_anomaly: false
devices: '1'
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
in_channels: 3
inference_mode: true
ipus: null
learning_rate: 0.005
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
load_config: null
log_every_n_steps: 50
logger: true
max_epochs: 40
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model: resnet18
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_classes: 65
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 4
overfit_batches: 0.0
plugins: null
precision: 32
pretrained: False
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save: null
split: RealWorld
strategy: null
sync_batchnorm: false
test: false
tpu_cores: null
track_grad_norm: -1
train: false
train_and_test: false
train_val_split: 0.2
val_check_interval: null
wandb_project: cbnn
weight_decay: 0.0005
