accelerator: gpu
accumulate_grad_batches: null
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_norm_track_running_stats: false
batch_size: 64
benchmark: null
check_val_every_n_epoch: 1
inference_context_collator: sum_optim
context_inference_weight: 0.4
context_split_mi_weight: 0.0
context_kld_weight: 1.0e-06
data: CIFAR10_OOD
data_dir: data/CIFAR10/
default_root_dir: null
detect_anomaly: false
devices: '1'
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
decoder_hidden_dims:
- 32
- 64
- 128
- 256
- 512
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
ic_mi_weight: 0.0
image_dim: 32
in_channels: 3
inference_mode: true
inference_num_layers: 1
inverse_context: false
ipus: null
kld_weight: 1.0e-06
l2_regularisation: 0.0
latent_dim: 64
learning_rate: 0.01
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
load_config: null
log_every_n_steps: 50
logger: true
max_epochs: 20
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
mode: inference
model: cbresenc
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
nb_input_images: 1
num_classes: 10
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 4
overfit_batches: 0.0
perturbation: 0.1
plugins: null
precision: 32
profiler: null
recon_weight: 0.0
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
sample_context_from_distribution: true
save: lightning_logs/version_354/checkpoints/epoch=19-step=12500.ckpt
split: null
split_recons_infer_latents: null
strategy: null
sync_batchnorm: false
test: true
tpu_cores: null
track_grad_norm: -1
train: false
train_and_test: false
train_val_split: 0.2
val_check_interval: null
w_kld_weight: 1.0e-06
w_samples: 16
wandb_project: cbnn
wc_mi_weight: 0.0
weight_decay: 1.0e-04
weight_pseudo_riemann_regularisation: 0.01
z_samples: 16
