accelerator: null
accumulate_grad_batches: null
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 32
benchmark: null
check_val_every_n_epoch: 1
data: CIFAR10
data_dir: ./data/CIFAR-10/
default_root_dir: null
detect_anomaly: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
hidden_dims:
- 32
- 64
- 128
- 256
- 512
in_channels: 3
image_dim: 32
inference_mode: true
ipus: null
kld_weight: 1.0
latent_dim: 256
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
load_config: null
log_every_n_steps: 50
logger: true
max_epochs: 20
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model: vae
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 4
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save: null
strategy: null
sync_batchnorm: false
test: false
tpu_cores: null
track_grad_norm: -1
train: false
train_and_test: false
train_val_split: 0.2
val_check_interval: null
wandb_project: null
